name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_KEY }}

      - name: Terraform Destroy
        run: |
          cd terraform
          terraform init
          terraform destroy -auto-approve \
            -var="do_api_key=${{ secrets.DO_API_KEY }}" \
            -var="do_ssh_public_key=${{ secrets.DO_SSH_PUBLIC_KEY }}" \
            -var="cloudflare_api_key=${{ secrets.CF_API_KEY }}" \
            -var="cloudflare_zone_id=${{ secrets.CF_ZONE_ID }}"
